# Generated by Django 4.2.30 on 2026-10-06 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('internal_length_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('internal_width_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('internal_height_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'ordering': ['cost', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('length_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('width_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipping.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shipping.product')),
            ],
            options={
                'unique_together': {('order', 'product')},
            },
        ),
    ]
